### PR TITLE
Create PSUADE MOAT method

### PR DESCRIPTION
**Pull request by kbarnhart**
This PR addresses issue #60 by creating a dakotathon implementation of the PSUADE MOAT method. 

@mdpiper I've done my best to follow your prior work in developing tests. If there are standard method tests that I've missed, please let me know and I'll write them.

### CODE REVIEW

**Comment by kbarnhart** [comment]
@mdpiper I'm getting close to doing some additional work on Dakotathon (adding a calibration method). 

Before I start I'd appreciate any feedback on how I implemented this method. Should I do the new method in a vastly different way?

**Comment by mdpiper** [comment]
@kbarnhart I'll start reviewing this PR this week. (I'm in the midst of writing a report for NSF due Friday.) I'm sorry I've taken so long in getting to this.

**Comment by kbarnhart** [comment]
@mdpiper no worries. good luck with report!

**Comment by mdpiper** [comment]
@kbarnhart This PR looks great! I'll merge it. Thank you so much for contributing to this project!

**Pull request merged**
