### PR TITLE
Changes for python 3 compatability

### PR DESCRIPTION
**Pull request by kbarnhart**
This PR addresses Issue #50 related to installing on python 3.

### CODE REVIEW

**Comment by mcflugen** [comment]
I think a better solution is to remove `ez_setup.py` all together and specify `setuptools` (>= 18.0, I think) as a build requirement.

**Comment by kbarnhart** [comment]
Does it also make sense to change the CI to check python 3.5 in addition to python 2.7?

I, however, don't know what the initial intentions for dakotathon compatibility were.

**Comment by mdpiper** [comment]
@kbarnhart I wrote Dakotathon with Python 2.7 for compatibility with the rest of the CSDMS software stack. However, I'm pretty sure that @mcflugen has been going back and making sure that the parts of the stack that can be upgraded to Python 3, are. This is probably as good a time as any to upgrade Dakotathon. I'd estimate it would take a day or two to set this up in Travis CI and make sure all the tests pass.

@mcflugen I agree. I'll remove `ez_setup.py`.

**Comment by kbarnhart** [comment]
This PR may be superseded by PR #59 which addresses python 3 compatibility for all of dakotathon, not just the install.

**Comment by mdpiper** [comment]
@kbarnhart I'm closing this PR in anticipation of #59, but I merged your commit 90156fa.
@mcflugen I took your advice, specifying `setuptools` as a package and removing `ez_setup.py`.

**Pull request merged**
